
--------------------------------------------------------------------;
-- DOWN
--------------------------------------------------------------------;

DROP TABLE ART46.PLANNING_MARKERING;

DROP TABLE ART46.PLANNING_VERSIE_MARKERING;


delete from  ART46.DB_VERSIE
where DB_VERSIE = '3.02.53';

--------------------------------------------------------------------;
-- UP
--------------------------------------------------------------------;

CREATE TABLE ART46.PLANNING_MARKERING
(
   MARKERING_ID smallint not null generated by default as identity(START WITH 1),
   OMSCHRIJVING varchar(60) not null,
   creatie_ts timestamp not null default current timestamp,
   creatie_user varchar(25) not null,
   PRIMARY KEY (MARKERING_ID)
)
;


CREATE TABLE ART46.PLANNING_VERSIE_MARKERING
(
   DOSS_HDR_ID VARCHAR(8) not null,
   PLANNING_VERSIE smallint not null,
   MARKERING_ID smallint not null,
   PRIMARY KEY (DOSS_HDR_ID, PLANNING_VERSIE, MARKERING_ID),
   FOREIGN KEY FK_PLVM_PLANNING_VERSIE(DOSS_HDR_ID, PLANNING_VERSIE)
           REFERENCES ART46.PLANNING_VERSIE (DOSS_HDR_ID, PLANNING_VERSIE) ON DELETE RESTRICT,
   FOREIGN KEY FK_PLVM_PLANNING_MARKERING(MARKERING_ID)
           REFERENCES ART46.PLANNING_MARKERING (MARKERING_ID) ON DELETE RESTRICT
)
;



-- deze versie van de wijzigingen in db registreren.
insert into ART46.DB_VERSIE(DB_VERSIE) values ('3.02.53');
