

--------------------------------------------------------------------;
-- DOWN
--------------------------------------------------------------------;

drop table art46.dossier_instrument;

drop table art46.verontreinig_activiteit;

delete from  art46.db_versie
where db_versie = '5.33';

--------------------------------------------------------------------;
-- UP
--------------------------------------------------------------------;

create table art46.verontreinig_activiteit (
    id int not null generated by default as identity (START WITH 1),
    activiteit_type_id int not null,
    overdracht_id int,
    dossier_id int,
    dossier_type char(1) not null,
    primary key (id),
    foreign key fk_verontact_type (activiteit_type_id)
         references art46.verontreinig_activiteit_type (activiteit_type_id)
         on delete restrict,
    foreign key fk_verontact_overdracht (overdracht_id)
         references art46.dossier_overdracht (overdracht_id)
         on delete restrict,
    foreign key fk_verontact_dossier (dossier_id)
         references art46.dossier (id)
         on delete restrict,
    foreign key fk_verontact_dossier_type (dossier_type)
         references art46.dossier_type (dossier_type)
         on delete restrict
);


create table art46.dossier_instrument (
    id int not null generated by default as identity (START WITH 1),
    instrument_type_id int not null,
    overdracht_id int,
    dossier_id int,
    dossier_type char(1) not null,
    primary key (id),
    foreign key fk_dosinstr_type (instrument_type_id)
         references art46.instrument_type (instrument_type_id)
         on delete restrict,
    foreign key fk_dosinstr_overdracht (overdracht_id)
         references art46.dossier_overdracht (overdracht_id)
         on delete restrict,
    foreign key fk_dosinstr_dossier (dossier_id)
         references art46.dossier (id)
         on delete restrict,
    foreign key fk_dosinstr_dossier_type (dossier_type)
         references art46.dossier_type (dossier_type)
         on delete restrict
);


-- deze versie van de wijzigingen in db registreren.
insert into art46.db_versie(db_versie) values ('5.33');