

--------------------------------------------------------------------;
-- DOWN
--------------------------------------------------------------------;

drop trigger smeg.i_dossier_art46;
create trigger smeg.i_dossier_art46 after
insert on smeg.dossier referencing new as nrow for each row mode db2sql
insert into art46.dossier
(
   id, dossier_id, dossier_id_boa, dossier_type, dossier_fase_id
)
values
(
   (select max(id) + 1 from art46.dossier),
   '_' || rtrim(cast(nrow.dossier_id as char(10))),
   nrow.dossier_id,
   'b',
   13
)
;


CREATE TRIGGER art46_dossier_id NO CASCADE BEFORE
INSERT ON ART46.DOSSIER REFERENCING NEW AS n FOR EACH ROW MODE DB2SQL set n.id =
(
   select
   max(id) + 1
   from ART46.DOSSIER
)

delete from  art46.db_versie
where db_versie = '6.04';

--------------------------------------------------------------------;
-- UP
--------------------------------------------------------------------;

drop trigger db2inst1.art46_dossier_id;

drop trigger smeg.art46_dossier_id;

drop trigger smeg.i_dossier_art46;
create trigger smeg.i_dossier_art46 after
insert on smeg.dossier referencing new as nrow for each row mode db2sql
insert into art46.dossier
(
   dossier_id, dossier_id_boa, dossier_type, dossier_fase_id
)
values
(
    '_' || rtrim(cast(nrow.dossier_id as char(10))),
    nrow.dossier_id,
    'B',
    13
)
;



select
    dos.*
from art46.v_dossier dos
where 1 = 1
order by id desc
;

alter table art46.dossier
    alter column id set generated by default as identity (START WITH 54000);


-- deze versie van de wijzigingen in db registreren.
insert into art46.db_versie(db_versie) values ('6.04');
