
alter table ART46.MEETSTAAT_SCHULDVORDERING ADD COLUMN UPDATED TIMESTAMP;
ALTER TABLE ART46.MEETSTAAT_SCHULDVORDERING ADD COLUMN DEELOPDRACHT_ID INT;
ALTER TABLE ART46.MEETSTAAT_SCHULDVORDERING ADD COLUMN UPDATE TIMESTAMP;
CALL SYSPROC.ADMIN_CMD('REORG TABLE ART46.MEETSTAAT_SCHULDVORDERING');


alter table ART46.MEETSTAAT_SCHULDVORDERING alter column INGEZONDEN SET DATA TYPE TIMESTAMP;
CALL SYSPROC.ADMIN_CMD('REORG TABLE ART46.MEETSTAAT_SCHULDVORDERING');

alter table ART46.MEETSTAAT_SCHULDVORDERING alter column VAN_DATUM SET DATA TYPE TIMESTAMP;
CALL SYSPROC.ADMIN_CMD('REORG TABLE ART46.MEETSTAAT_SCHULDVORDERING');

alter table ART46.MEETSTAAT_SCHULDVORDERING alter column TOT_DATUM SET DATA TYPE TIMESTAMP;
CALL SYSPROC.ADMIN_CMD('REORG TABLE ART46.MEETSTAAT_SCHULDVORDERING');

alter table ART46.MEETSTAAT_SCHULDVORDERING
   add constraint FK_MSV_OFFERTE foreign key (offerte_id)
      references ART46.OFFERTE (id)
      on delete restrict on update restrict
;





ALTER TABLE ART46.SCHULDVORDERING ADD "ACCEPTATIE_D" date;
ALTER TABLE ART46.SCHULDVORDERING ADD COLUMN ANTWOORD_PDF_BRIEF_ID INT;
ALTER TABLE ART46.SCHULDVORDERING ADD "BRIEFCATEGORIE_ID" int;
ALTER TABLE ART46.SCHULDVORDERING ADD COLUMN AANVRAAG_PDF_BRIEF_ID INT;
ALTER TABLE ART46.SCHULDVORDERING ADD COLUMN PRINT_D DATE;
ALTER TABLE ART46.SCHULDVORDERING ALTER VORDERING_NR SET DATA TYPE VARCHAR(40);
CALL SYSPROC.ADMIN_CMD('REORG TABLE ART46.SCHULDVORDERING');

alter table ART46.SCHULDVORDERING
   add constraint FK_SV_ANTWOORD_PDF_BRIEF foreign key (ANTWOORD_PDF_BRIEF_ID)
      references ART46.BRIEF (brief_id)
      on delete restrict on update restrict
;

alter table ART46.SCHULDVORDERING
   add constraint FK_SV_AANVRAAG_PDF_BRIEF foreign key (AANVRAAG_PDF_BRIEF_ID)
      references ART46.BRIEF (brief_id)
      on delete restrict on update restrict
;








ALTER TABLE ART46.SCHULDVORDERING_STATUS_HISTORY ADD "MOTIVATIE" VARCHAR(1024);
CALL SYSPROC.ADMIN_CMD('REORG TABLE ART46.SCHULDVORDERING_STATUS_HISTORY');

alter table ART46.SCHULDVORDERING_STATUS_HISTORY alter column DATUM SET DATA TYPE TIMESTAMP;
CALL SYSPROC.ADMIN_CMD('REORG TABLE ART46.SCHULDVORDERING_STATUS_HISTORY');






ALTER TABLE ART46.DEELOPDRACHT ADD "OFFERTE_ID" INT;
CALL SYSPROC.ADMIN_CMD('REORG TABLE ART46.DEELOPDRACHT');

alter table ART46.DEELOPDRACHT
   add constraint FK_DO_OFFERTE foreign key (OFFERTE_ID)
      references ART46.OFFERTE (id)
      on delete restrict on update restrict
;






CREATE TABLE ART46.SCHULDVORDERING_STATUS
(
  KEY varchar(255) not null PRIMARY KEY ,
  NAME varchar(255),
  NAME_WEB_LOKER varchar(255)
);


INSERT INTO ART46.SCHULDVORDERING_STATUS (KEY,NAME,NAME_WEB_LOKER) VALUES ('VERZONDEN','INGEDIEND','VERZONDEN');
INSERT INTO ART46.SCHULDVORDERING_STATUS (KEY,NAME,NAME_WEB_LOKER) VALUES ('GEACCEPTEERD','GEACCEPTEERD','VERZONDEN');
INSERT INTO ART46.SCHULDVORDERING_STATUS (KEY,NAME,NAME_WEB_LOKER) VALUES ('GEACCEPTEERD MET AANPASSINGEN','GEACCEPTEERD MET AANPASSINGEN','VERZONDEN');
INSERT INTO ART46.SCHULDVORDERING_STATUS (KEY,NAME,NAME_WEB_LOKER) VALUES ('GOEDGEKEURD','GOEDGEKEURD','GOEDGEKEURD');
INSERT INTO ART46.SCHULDVORDERING_STATUS (KEY,NAME,NAME_WEB_LOKER) VALUES ('GOEDGEKEURD MET AANPASSINGEN','GOEDGEKEURD MET AANPASSINGEN','GOEDGEKEURD MET AANPASSINGEN');
INSERT INTO ART46.SCHULDVORDERING_STATUS (KEY,NAME,NAME_WEB_LOKER) VALUES ('AFGEKEURD','AFGEKEURD','AFGEKEURD');
INSERT INTO ART46.SCHULDVORDERING_STATUS (KEY,NAME,NAME_WEB_LOKER) VALUES ('IN OPMAAK','IN OPMAAK','IN OPMAAK');










ALTER TABLE ART46.OFFERTE ADD "KEY" varchar(35);
CALL SYSPROC.ADMIN_CMD('REORG TABLE ART46.OFFERTE');


CREATE TABLE ART46.VOORSTEL_DEELOPDRACHT(
  ID INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
  OFFERTE_ID INT,
  DOSSIER_ID INT,
  BEDRAG_EXCL_BTW FLOAT(53),
  BEDRAG_INCL_BTW FLOAT(53),
  OMSCHRIJVING varchar(60),
  STATUS  VARCHAR(24),
  AANVRAAG_DATUM TIMESTAMP,
  ANTWOORD_DATUM TIMESTAMP,
  BESLISSINGS_DATUM TIMESTAMP
);



CREATE TABLE ART46.VOORSTEL_DEELOPDRACHT_REGEL
(
  ID                       INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
  OFFERTE_REGEL_ID         INT,
  VOORSTEL_DEELOPDRACHT_ID INT NOT NULL,
  AFNAMEBEDRAG             FLOAT(53),
  AFNAME                   FLOAT(53),
  BESCHRIJVING             VARCHAR(512),
  OPMERKING                VARCHAR(512),
  BTW_TARIEF               INT,
  MEERWERKEN_EENHEIDSPRIJS FLOAT(53),
  MEERWERKEN_TYPE          CHAR(10),
  MEERWERKEN_EENHEID       CHAR(10),
  FOREIGN KEY (VOORSTEL_DEELOPDRACHT_ID) REFERENCES ART46.VOORSTEL_DEELOPDRACHT (ID),
  FOREIGN KEY (OFFERTE_REGEL_ID) REFERENCES ART46.OFFERTE_REGEL (ID)
);




CREATE TABLE ART46.VOORSTEL_DEELOPDRACHT_STATUS
(
  KEY varchar(255) not null PRIMARY KEY,
  NAME varchar(255),
  NAME_WEB_LOKER varchar(255)
);
INSERT INTO ART46.VOORSTEL_DEELOPDRACHT_STATUS (KEY,NAME,NAME_WEB_LOKER) VALUES ('IN_OPMAAK','IN OPMAAK','');
INSERT INTO ART46.VOORSTEL_DEELOPDRACHT_STATUS (KEY,NAME,NAME_WEB_LOKER) VALUES ('IN_AANVRAAG','IN_AANVRAAG','AANVRAAG');
INSERT INTO ART46.VOORSTEL_DEELOPDRACHT_STATUS (KEY,NAME,NAME_WEB_LOKER) VALUES ('TOEGEKEND','TOEGEKEND','TOEGEKEND');
INSERT INTO ART46.VOORSTEL_DEELOPDRACHT_STATUS (KEY,NAME,NAME_WEB_LOKER) VALUES ('BEOORDELEN','BEOORDELEN','In Behandeling');
INSERT INTO ART46.VOORSTEL_DEELOPDRACHT_STATUS (KEY,NAME,NAME_WEB_LOKER) VALUES ('AFGEKEURD','AFGEKEURD','AFGEKEURD');






ALTER TABLE ART46.DEELOPDRACHT ADD COLUMN VOORSTEL_DEELOPDRACHT_ID INT;
ALTER TABLE ART46.DEELOPDRACHT ADD FOREIGN KEY FK_DO_VOORSTEL (VOORSTEL_DEELOPDRACHT_ID) REFERENCES ART46.VOORSTEL_DEELOPDRACHT (ID);
CALL SYSPROC.ADMIN_CMD('REORG TABLE ART46.DEELOPDRACHT');


CREATE TABLE ART46.VOORSTEL_DEELOPDRACHT_HISTORY
(
  ID INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
  VOORSTEL_DEELOPDRACHT_ID INT,
  GEBRUIKER_ID VARCHAR(120),
  DOSSIERHOUDER_ID VARCHAR(8),
  DATUM TIMESTAMP,
  STATUS VARCHAR(30),
  MOTIVATIE VARCHAR(1024),
  FOREIGN KEY ( DOSSIERHOUDER_ID ) REFERENCES ART46.DOSSIER_HOUDER ( DOSS_HDR_ID ),
  FOREIGN KEY ( VOORSTEL_DEELOPDRACHT_ID ) REFERENCES ART46.VOORSTEL_DEELOPDRACHT ( ID )
);



-- ???????????????????????????????????????????????
--   stond in acc , niet in prd.
--  geeft fout bij ophalen sv.
--    -> toegevoegd in prd.
--  is in acc nergens ingevuld... , geen fk gedefinieerd, ...
--  waar dient dit veld voor.

alter table ART46.SCHULDVORDERING_SAP_PROJECT
    add column aanvraagid int
;
CALL SYSPROC.ADMIN_CMD('REORG TABLE ART46.SCHULDVORDERING_SAP_PROJECT');

-- deze versie van de wijzigingen in db registreren.
insert into ART46.DB_VERSIE(DB_VERSIE) values ('4.21');

