--------------------------------------------------------------------;
-- DOWN
--------------------------------------------------------------------;

call sysproc.admin_cmd('reorg table art46.SCHULDVORDERING');


delete from  art46.db_versie
where db_versie = '4.61';



--------------------------------------------------------------------;
-- UP
--------------------------------------------------------------------;

select max(sv.VORDERING_ID)
from art46.SCHULDVORDERING sv
; -- 6924 9347

alter table art46.schuldvordering alter column vordering_id set generated by default as identity (
START WITH 9360);
call sysproc.admin_cmd('reorg table art46.SCHULDVORDERING');



select max(sv.ID)
from art46.offerte sv
; -- 115 535

alter table art46.offerte alter column id set generated by default as identity (START WITH 540);
call sysproc.admin_cmd('reorg table art46.offerte');



select max(sv.ID)
from art46.offerte_regel sv
; -- 10892  47248

alter table art46.offerte_regel alter column id set generated by default as identity (START WITH 47250);
call sysproc.admin_cmd('reorg table art46.offerte_regel');



select max(sv.ID)
from art46.WEBLOKET_GEBRUIKER sv
; -- 19

alter table art46.WEBLOKET_GEBRUIKER alter column id set generated by default as identity (START WITH 100);
call sysproc.admin_cmd('reorg table art46.WEBLOKET_GEBRUIKER');




alter table art46.WEBLOKET_GEBRUIKER_OFFERTE
    add primary key(gebruiker_id, offerte_id);

call sysproc.admin_cmd('reorg table art46.WEBLOKET_GEBRUIKER_OFFERTE');

-- deze versie van de wijzigingen in db registreren.
insert into art46.db_versie(db_versie) values ('4.61');