
--------------------------------------------------------------------;
-- DOWN
--------------------------------------------------------------------;


delete from  ART46.DB_VERSIE
where DB_VERSIE = '4.06';

--------------------------------------------------------------------;
-- UP
--------------------------------------------------------------------;



CREATE TABLE ART46.WEBLOKET_GEBRUIKER
(
    id int PRIMARY KEY NOT NULL,
    email_address VARCHAR (120) NOT NULL,
    active VARCHAR(6) NOT NULL
);

ALTER TABLE ART46.WEBLOKET_GEBRUIKER
 ADD CONSTRAINT unique_id UNIQUE (id);
CALL SYSPROC.ADMIN_CMD('REORG TABLE ART46.WEBLOKET_GEBRUIKER');


CREATE TABLE ART46.MEETSTAAT_SCHULDVORDERING (
  id int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
  offerte_id INT NOT NULL,
  beschrijving VARCHAR(128),
  ingezonden DATE ,
  bedrag_excl_btw FLOAT(53),
  status VARCHAR (20)
);

CREATE TABLE ART46.MEETSTAAT_SCHULDVORDERING_REGEL (
  SCHULDVORDERING_REGEL_ID int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
  offerte_regel_id INT NOT NULL,
  SchuldvorderingId INT NOT NULL,
  afnameBedrag FLOAT(53),
  afname FLOAT(53)
);

CREATE TABLE ART46.SCHULDVORDERING_STATUS_HISTORY (
  id int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
  schuldvordering_id int NOT NULL,
  gebruiker_id VARCHAR (120),
  dossierHouder_id VARCHAR(8),
  datum DATE,
  status VARCHAR (20)
);


CREATE TABLE ART46.VOORSTEL_DEEL_OPDRACHT (
  id int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
  offerte_id INT NOT NULL,
  beschrijving VARCHAR(128),
  naam VARCHAR(128),
  status VARCHAR (20),
  DEELOPDRACHT_ID INT
);


CREATE TABLE ART46.VOORSTEL_DEEL_OPDRACHT_REGEL (
  VOORSTEL_DEEL_OPDRACHT_REGE_ID int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
  offerte_regel_id INT NOT NULL,
  voorstelDeelopdrachtId INT NOT NULL,
  afnameBedrag FLOAT(53),
  afname FLOAT(53)
);


ALTER TABLE ART46.OFFERTE_REGEL ADD beschrijving VARCHAR(512);
ALTER TABLE ART46.OFFERTE_REGEL ADD btw_tarief INT;
CALL SYSPROC.ADMIN_CMD('REORG TABLE ART46.OFFERTE_REGEL');

ALTER TABLE ART46.MEETSTAAT_SCHULDVORDERING_REGEL ADD btw_tarief INT;
ALTER TABLE ART46.MEETSTAAT_SCHULDVORDERING_REGEL ADD GECORRIGEERD_BTW_TARIEF INT;
ALTER TABLE ART46.MEETSTAAT_SCHULDVORDERING_REGEL ALTER COLUMN OFFERTE_REGEL_ID DROP NOT NULL;
ALTER TABLE ART46.MEETSTAAT_SCHULDVORDERING_REGEL  ADD MEERWERKEN_EENHEIDSPRIJS FLOAT(53);
ALTER TABLE ART46.MEETSTAAT_SCHULDVORDERING_REGEL  ADD GECORRIGEERD_MEERWERKEN_EENHEIDSPRIJS FLOAT(53);
CALL SYSPROC.ADMIN_CMD('REORG TABLE ART46.MEETSTAAT_SCHULDVORDERING_REGEL');

ALTER TABLE ART46.MEETSTAAT_SCHULDVORDERING ADD bedrag_incl_btw FLOAT(53);
ALTER TABLE ART46.MEETSTAAT_SCHULDVORDERING ALTER STATUS SET DATA TYPE varchar(30);
CALL SYSPROC.ADMIN_CMD('REORG TABLE ART46.MEETSTAAT_SCHULDVORDERING');

ALTER TABLE ART46.SCHULDVORDERING ADD aanvraag_schuldvordering_id integer;
CALL SYSPROC.ADMIN_CMD('REORG TABLE ART46.SCHULDVORDERING');

ALTER TABLE ART46.SCHULDVORDERING_STATUS_HISTORY ALTER STATUS SET DATA TYPE varchar(30);
CALL SYSPROC.ADMIN_CMD('REORG TABLE ART46.SCHULDVORDERING_STATUS_HISTORY');


-- deze versie van de wijzigingen in db registreren.
insert into ART46.DB_VERSIE(DB_VERSIE) values ('4.06');
