
--------------------------------------------------------------------;
-- DOWN
--------------------------------------------------------------------;


delete from  ART46.DB_VERSIE
where DB_VERSIE = '4.02';

--------------------------------------------------------------------;
-- UP
--------------------------------------------------------------------;

CREATE TABLE ART46.PLANNING_DOSSIER_VERSIE
(
   DOSSIER_ID integer not null,
   PLANNING_VERSIE smallint not null,
   wijzig_ts timestamp not null default current timestamp,
   wijzig_user varchar(25) not null,
   PRIMARY KEY (DOSSIER_ID, PLANNING_VERSIE),
   FOREIGN KEY FK_PLDV_DOSSIER(DOSSIER_ID)
           REFERENCES ART46.DOSSIER (ID) ON DELETE RESTRICT
)
;


INSERT INTO "ART46"."PLANNING_DOSSIER_VERSIE" (DOSSIER_ID, PLANNING_VERSIE, WIJZIG_USER)
select distinct dossier_id, PLANNING_VERSIE, 'user'
from art46.PLANNING_LIJN_VERSIE plv
where planning_versie  = 1
;


INSERT INTO "ART46"."PLANNING_DOSSIER_VERSIE" (DOSSIER_ID,PLANNING_VERSIE,WIJZIG_TS,WIJZIG_USER)
select distinct dossier_id, PLANNING_VERSIE, WIJZIG_TS, WIJZIG_USER
from art46.PLANNING_LIJN_VERSIE plv
where planning_versie > 1
;


ALTER TABLE ART46.PLANNING_LIJN_VERSIE
	Add column PLANNING_DOSSIER_VERSIE smallint not null default 0
;

update ART46.PLANNING_LIJN_VERSIE
set PLANNING_DOSSIER_VERSIE = planning_versie
;


ALTER TABLE ART46.PLANNING_LIJN_VERSIE
   add FOREIGN KEY FK_PLLV_PLANNING_DOSSIER_VERSIE (DOSSIER_ID, PLANNING_DOSSIER_VERSIE)
           REFERENCES ART46.PLANNING_DOSSIER_VERSIE (DOSSIER_ID, PLANNING_VERSIE) ON DELETE RESTRICT
;


ALTER TABLE ART46.PLANNING_LIJN_VERSIE
	drop FOREIGN KEY FK_PLLV_PLANNING_LIJN
;

ALTER TABLE ART46.PLANNING_LIJN_VERSIE
   add FOREIGN KEY FK_PLLV_PLANNING_LIJN (LIJN_ID)
           REFERENCES ART46.PLANNING_LIJN (lijn_id) ON DELETE RESTRICT
;



ALTER TABLE ART46.PLANNING_LIJN_VERSIE
	drop FOREIGN KEY FK_PLLV_PLANNING_VERSIE
;

ALTER TABLE ART46.PLANNING_LIJN_VERSIE
	drop PRIMARY KEY
;

ALTER TABLE ART46.PLANNING_LIJN_VERSIE
	ADD PRIMARY KEY(lijn_id, planning_dossier_versie)
;


ALTER TABLE ART46.PLANNING_LIJN_VERSIE
	alter column commentaar SET DATA TYPE VARCHAR(1000)
;

ALTER TABLE ART46.PLANNING_LIJN_VERSIE
	alter column DOSS_HDR_ID drop not null
;

ALTER TABLE ART46.PLANNING_LIJN_VERSIE
	alter column PLANNING_VERSIE drop not null
;

call sysproc.admin_cmd('reorg table ART46.PLANNING_LIJN_VERSIE')
;




ALTER TABLE ART46.PLANNING_LIJN
    drop CONSTRAINT DOSSIER_ID_UNIEK
;

ALTER TABLE ART46.PLANNING_LIJN
   drop column  DOSS_HDR_ID
;

call sysproc.admin_cmd('reorg table ART46.PLANNING_LIJN')
;


CREATE TABLE ART46.PLANNING_DOSSIER_VERSIE_MARKERING
(
   DOSSIER_ID integer not null,
   PLANNING_VERSIE smallint not null,
   MARKERING_ID smallint not null,
   PRIMARY KEY (DOSSIER_ID, PLANNING_VERSIE, MARKERING_ID),
   FOREIGN KEY FK_PLDVM_PLANNING_DOSSIER_VERSIE(DOSSIER_ID, PLANNING_VERSIE)
           REFERENCES ART46.PLANNING_DOSSIER_VERSIE (DOSSIER_ID, PLANNING_VERSIE) ON DELETE RESTRICT,
   FOREIGN KEY FK_PLDVM_PLANNING_MARKERING(MARKERING_ID)
           REFERENCES ART46.PLANNING_MARKERING (MARKERING_ID) ON DELETE RESTRICT
)
;


ALTER TABLE ART46.PLANNING_VERSIE
    DROP FOREIGN KEY FK_PLV_PLANNING

ALTER TABLE ART46.PLANNING_VERSIE
    ADD FOREIGN KEY FK_PLV_DOSSIER_HOUDER(DOSS_HDR_ID)
           REFERENCES ART46.DOSSIER_HOUDER (DOSS_HDR_ID) ON DELETE RESTRICT
;

-- deze versie van de wijzigingen in db registreren.
insert into ART46.DB_VERSIE(DB_VERSIE) values ('4.02');
