--------------------------------------------------------------------;
-- DOWN
--------------------------------------------------------------------;


delete from  art46.db_versie
where db_versie = '4.57';



--------------------------------------------------------------------;
-- UP
--------------------------------------------------------------------;


CREATE TABLE ART46.BESTEK_ADRES_copy
(
   BESTEK_ID int NOT NULL,
   ADRES_ID int NOT NULL,
   CONTACT_ID int NOT NULL
)
;

insert into ART46.BESTEK_ADRES_copy
select * from ART46.BESTEK_ADRES
;

drop table ART46.BESTEK_ADRES;

CREATE TABLE ART46.BESTEK_ADRES
(
   BESTEK_ADRES_ID int not null generated by default as identity (start with 100),
   BESTEK_ID int NOT NULL,
   ADRES_ID int NOT NULL,
   CONTACT_ID int,
   primary key (BESTEK_ADRES_ID)
)
;

insert into ART46.BESTEK_ADRES (BESTEK_ID, ADRES_ID, CONTACT_ID)
select BESTEK_ID, ADRES_ID, CONTACT_ID from ART46.BESTEK_ADRES_copy order by BESTEK_ID, ADRES_ID, CONTACT_ID
;


alter table art46.AANVRAAGVASTLEGGING
    add column opdrachthouder_id int
;

update art46.AANVRAAGVASTLEGGING av
set av.OPDRACHTHOUDER_ID = (select distinct ba.BESTEK_ADRES_ID
                            from art46.BESTEK_ADRES ba
                            where av.OPDRACHTHOUDER = ba.ADRES_ID || ',' ||ba.CONTACT_ID
                                  and av.BESTEKID = ba.BESTEK_ID
                            )
;


update art46.BESTEK_ADRES ba
set ba.CONTACT_ID = null
where 1 = 1
    and ba.CONTACT_ID = 0


-- deze versie van de wijzigingen in db registreren.
insert into art46.db_versie(db_versie) values ('4.57');