
alter table ART46.DOSSIER
	drop column PROGRAMMA_CODE,
	drop constraint FK_DO_PROGRAMMA
;

DROP TRIGGER ART46.BI_PROGRAMMA_TYPE_TS  
;

DROP TRIGGER ART46.BU_PROGRAMMA_TYPE_TS   
;

drop TABLE ART46.PROGRAMMA_TYPE
;

delete from  ART46.DB_VERSIE
where DB_VERSIE = '2.08.4';
