

-- ART46.DOSSIER

CREATE TRIGGER ART46.bi_dossier_ts  
NO CASCADE BEFORE INSERT ON art46.dossier
REFERENCING
    NEW AS post
FOR EACH ROW MODE DB2SQL
SET
        post.creatie_ts = CURRENT TIMESTAMP,
        post.wijzig_ts = CURRENT TIMESTAMP
;


CREATE TRIGGER ART46.bu_dossier_ts  
NO CASCADE BEFORE UPDATE ON art46.dossier
REFERENCING
    OLD AS pre
    NEW AS post
FOR EACH ROW MODE DB2SQL
SET
        post.wijzig_ts = CURRENT TIMESTAMP
;

-- SAP.PROJECT

CREATE TRIGGER SAP.BI_PROJECT_TS  
NO CASCADE BEFORE INSERT ON SAP.PROJECT
REFERENCING
    NEW AS post
FOR EACH ROW MODE DB2SQL
SET
        post.creatie_ts = CURRENT TIMESTAMP,
        post.wijzig_ts = CURRENT TIMESTAMP
;


CREATE TRIGGER SAP.BU_PROJECT_TS   
NO CASCADE BEFORE UPDATE ON SAP.PROJECT
REFERENCING
    OLD AS pre
    NEW AS post
FOR EACH ROW MODE DB2SQL
SET
        post.wijzig_ts = CURRENT TIMESTAMP
;


-- ART46.SCHULDVORDERING

CREATE TRIGGER ART46.BI_SCHULDVORDERING_TS  
NO CASCADE BEFORE INSERT ON ART46.SCHULDVORDERING
REFERENCING
    NEW AS post
FOR EACH ROW MODE DB2SQL
SET
        post.creatie_ts = CURRENT TIMESTAMP,
        post.wijzig_ts = CURRENT TIMESTAMP
;


CREATE TRIGGER ART46.BU_SCHULDVORDERING_TS   
NO CASCADE BEFORE UPDATE ON ART46.SCHULDVORDERING
REFERENCING
    OLD AS pre
    NEW AS post
FOR EACH ROW MODE DB2SQL
SET
        post.wijzig_ts = CURRENT TIMESTAMP
;


-- ART46.BESTEK

CREATE TRIGGER ART46.BI_BESTEK_TS  
NO CASCADE BEFORE INSERT ON ART46.BESTEK
REFERENCING
    NEW AS post
FOR EACH ROW MODE DB2SQL
SET
        post.creatie_ts = CURRENT TIMESTAMP,
        post.wijzig_ts = CURRENT TIMESTAMP
;


CREATE TRIGGER ART46.BU_BESTEK_TS   
NO CASCADE BEFORE UPDATE ON ART46.BESTEK
REFERENCING
    OLD AS pre
    NEW AS post
FOR EACH ROW MODE DB2SQL
SET
        post.wijzig_ts = CURRENT TIMESTAMP
;


-- ART46.DEELOPDRACHT

CREATE TRIGGER ART46.BI_DEELOPDRACHT_TS  
NO CASCADE BEFORE INSERT ON ART46.DEELOPDRACHT
REFERENCING
    NEW AS post
FOR EACH ROW MODE DB2SQL
SET
        post.creatie_ts = CURRENT TIMESTAMP,
        post.wijzig_ts = CURRENT TIMESTAMP
;


CREATE TRIGGER ART46.BU_DEELOPDRACHT_TS   
NO CASCADE BEFORE UPDATE ON ART46.DEELOPDRACHT
REFERENCING
    OLD AS pre
    NEW AS post
FOR EACH ROW MODE DB2SQL
SET
        post.wijzig_ts = CURRENT TIMESTAMP
;

-- ART46.SCHULDVORDERING_SAP_PROJECT

CREATE TRIGGER ART46.BI_SVSP_TS  
NO CASCADE BEFORE INSERT ON ART46.SCHULDVORDERING_SAP_PROJECT
REFERENCING
    NEW AS post
FOR EACH ROW MODE DB2SQL
SET
        post.creatie_ts = CURRENT TIMESTAMP,
        post.wijzig_ts = CURRENT TIMESTAMP
;


CREATE TRIGGER ART46.BU_SVSP_TS   
NO CASCADE BEFORE UPDATE ON ART46.SCHULDVORDERING_SAP_PROJECT
REFERENCING
    OLD AS pre
    NEW AS post
FOR EACH ROW MODE DB2SQL
SET
        post.wijzig_ts = CURRENT TIMESTAMP
;


-- tabel met versie nummer van db schema

create table ART46.DB_VERSIE
(
   DB_VERSIE        VARCHAR(20)         NOT NULL,
   creatie_ts       timestamp           not null,
   wijzig_ts        timestamp           not null,
   primary key (DB_VERSIE)
);


CREATE TRIGGER ART46.BI_DB_VERSIE_TS  
NO CASCADE BEFORE INSERT ON ART46.DB_VERSIE
REFERENCING
    NEW AS post
FOR EACH ROW MODE DB2SQL
SET
        post.creatie_ts = CURRENT TIMESTAMP,
        post.wijzig_ts = CURRENT TIMESTAMP
;


CREATE TRIGGER ART46.BU_DB_VERSIE_TS   
NO CASCADE BEFORE UPDATE ON ART46.DB_VERSIE
REFERENCING
    OLD AS pre
    NEW AS post
FOR EACH ROW MODE DB2SQL
SET
        post.wijzig_ts = CURRENT TIMESTAMP
;

-- 

-- deze versie van de wijzigingen in db registreren.

insert into ART46.DB_VERSIE(DB_VERSIE) values ('2.06.4');
